### ISSUE TITLE
UnsatisfiedLinkError: Unable to load library 'libsystemd-journal'

### ISSUE THREAD

**Issue by bwaldvogel** [gnieh/logback-journal#1]
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'libsystemd-journal': Native library (linux-x86-64/liblibsystemd-journal.so) not found in resource path ([…])
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
    at com.sun.jna.Library$Handler.<init>(Library.java:147)
    at com.sun.jna.Native.loadLibrary(Native.java:412)
    at com.sun.jna.Native.loadLibrary(Native.java:391)
    at org.gnieh.logback.SystemdJournalLibrary.<clinit>(SystemdJournalLibrary.java:30)
    at org.gnieh.logback.SystemdJournalAppender.append(SystemdJournalAppender.java:97)
    at org.gnieh.logback.SystemdJournalAppender.append(SystemdJournalAppender.java:1)
    at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:85)
    at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
    at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:273)
    at ch.qos.logback.classic.Logger.callAppenders(Logger.java:260)
    at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:442)
    at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
    at ch.qos.logback.classic.Logger.info(Logger.java:600)
    at org.gnieh.logback.TestSimple.main(TestSimple.java:15)
```

**Comment by mshibanami** [comment]
@satabin 
I got same error with 0.1.0-SNAPSHOT.
Please apply the fix to maven repo.

**Comment by satabin** [comment]
Sorry I forgot to publish this one.
If it is usable enough as is, I will release the 0.1.0 with no further changes.

**Comment by mshibanami** [comment]
Thank you!!
